# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtbMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapid', models.CharField(max_length=256, verbose_name='mapid')),
                ('diff', models.CharField(max_length=256, verbose_name='name')),
                ('cs', models.CharField(max_length=8, verbose_name='cs')),
                ('ar', models.CharField(max_length=8, verbose_name='ar')),
                ('od', models.CharField(max_length=8, verbose_name='od')),
                ('hp', models.CharField(max_length=8, verbose_name='hp')),
                ('star', models.CharField(max_length=8, verbose_name='star')),
                ('url', models.CharField(max_length=256, verbose_name='cs')),
                ('bpm', models.CharField(max_length=8, verbose_name='bpm')),
                ('length', models.CharField(max_length=32, verbose_name='length')),
            ],
        ),
        migrations.CreateModel(
            name='ManiaMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapid', models.CharField(max_length=256, verbose_name='mapid')),
                ('map_id', models.CharField(max_length=256, verbose_name='did')),
                ('diff', models.CharField(max_length=256, verbose_name='name')),
                ('cs', models.CharField(max_length=8, verbose_name='cs')),
                ('ar', models.CharField(max_length=8, verbose_name='ar')),
                ('od', models.CharField(max_length=8, verbose_name='od')),
                ('hp', models.CharField(max_length=8, verbose_name='hp')),
                ('star', models.CharField(max_length=8, verbose_name='star')),
                ('url', models.CharField(max_length=256, verbose_name='cs')),
                ('bpm', models.CharField(max_length=8, verbose_name='bpm')),
                ('length', models.CharField(max_length=32, verbose_name='length')),
            ],
        ),
        migrations.CreateModel(
            name='MapSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('artist', models.CharField(max_length=256, verbose_name='artist')),
                ('url', models.CharField(max_length=256, verbose_name='url')),
                ('creator_url', models.CharField(max_length=256, verbose_name='creator_url')),
                ('creator', models.CharField(max_length=256, verbose_name='creator')),
                ('setid', models.CharField(max_length=256, verbose_name='setid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapid', models.CharField(max_length=256, verbose_name='mapid')),
                ('diff', models.CharField(max_length=256, verbose_name='name')),
                ('cs', models.CharField(max_length=8, verbose_name='cs')),
                ('ar', models.CharField(max_length=8, verbose_name='ar')),
                ('od', models.CharField(max_length=8, verbose_name='od')),
                ('hp', models.CharField(max_length=8, verbose_name='hp')),
                ('star', models.CharField(max_length=8, verbose_name='star')),
                ('url', models.CharField(max_length=256, verbose_name='cs')),
                ('bpm', models.CharField(max_length=8, verbose_name='bpm')),
                ('length', models.CharField(max_length=32, verbose_name='length')),
                ('setid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_maps', to='crawler.MapSet')),
            ],
        ),
        migrations.CreateModel(
            name='TaikoMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapid', models.CharField(max_length=256, verbose_name='mapid')),
                ('diff', models.CharField(max_length=256, verbose_name='name')),
                ('cs', models.CharField(max_length=8, verbose_name='cs')),
                ('ar', models.CharField(max_length=8, verbose_name='ar')),
                ('od', models.CharField(max_length=8, verbose_name='od')),
                ('hp', models.CharField(max_length=8, verbose_name='hp')),
                ('star', models.CharField(max_length=8, verbose_name='star')),
                ('url', models.CharField(max_length=256, verbose_name='cs')),
                ('bpm', models.CharField(max_length=8, verbose_name='bpm')),
                ('length', models.CharField(max_length=32, verbose_name='length')),
                ('setid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taiko_maps', to='crawler.MapSet')),
            ],
        ),
        migrations.RemoveField(
            model_name='ctbdiff',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='maniadiff',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='stddiff',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='taikodiff',
            name='mid',
        ),
        migrations.DeleteModel(
            name='CtbDiff',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='ManiaDiff',
        ),
        migrations.DeleteModel(
            name='StdDiff',
        ),
        migrations.DeleteModel(
            name='TaikoDiff',
        ),
        migrations.AddField(
            model_name='maniamap',
            name='set_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.MapSet'),
        ),
        migrations.AddField(
            model_name='maniamap',
            name='setid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mania_maps', to='crawler.MapSet'),
        ),
        migrations.AddField(
            model_name='ctbmap',
            name='setid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctb_maps', to='crawler.MapSet'),
        ),
    ]
