# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtbDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=256, verbose_name='did')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('cs', models.CharField(max_length=8, verbose_name='cs')),
                ('ar', models.CharField(max_length=8, verbose_name='ar')),
                ('od', models.CharField(max_length=8, verbose_name='od')),
                ('hp', models.CharField(max_length=8, verbose_name='hp')),
                ('star', models.CharField(max_length=8, verbose_name='star')),
                ('url', models.CharField(max_length=256, verbose_name='cs')),
                ('bpm', models.CharField(max_length=8, verbose_name='bpm')),
                ('length', models.CharField(max_length=32, verbose_name='length')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('artist', models.CharField(max_length=256, verbose_name='artist')),
                ('url', models.CharField(max_length=256, verbose_name='url')),
                ('creator_url', models.CharField(max_length=256, verbose_name='creator_url')),
                ('creator', models.CharField(max_length=256, verbose_name='creator')),
            ],
        ),
        migrations.CreateModel(
            name='ManiaDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=256, verbose_name='did')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('cs', models.CharField(max_length=8, verbose_name='cs')),
                ('ar', models.CharField(max_length=8, verbose_name='ar')),
                ('od', models.CharField(max_length=8, verbose_name='od')),
                ('hp', models.CharField(max_length=8, verbose_name='hp')),
                ('star', models.CharField(max_length=8, verbose_name='star')),
                ('url', models.CharField(max_length=256, verbose_name='cs')),
                ('bpm', models.CharField(max_length=8, verbose_name='bpm')),
                ('length', models.CharField(max_length=32, verbose_name='length')),
                ('mid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map_crawler.Info')),
            ],
        ),
        migrations.CreateModel(
            name='StdDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=256, verbose_name='did')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('cs', models.CharField(max_length=8, verbose_name='cs')),
                ('ar', models.CharField(max_length=8, verbose_name='ar')),
                ('od', models.CharField(max_length=8, verbose_name='od')),
                ('hp', models.CharField(max_length=8, verbose_name='hp')),
                ('star', models.CharField(max_length=8, verbose_name='star')),
                ('url', models.CharField(max_length=256, verbose_name='cs')),
                ('bpm', models.CharField(max_length=8, verbose_name='bpm')),
                ('length', models.CharField(max_length=32, verbose_name='length')),
                ('mid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map_crawler.Info')),
            ],
        ),
        migrations.CreateModel(
            name='TaikoDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=256, verbose_name='did')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('cs', models.CharField(max_length=8, verbose_name='cs')),
                ('ar', models.CharField(max_length=8, verbose_name='ar')),
                ('od', models.CharField(max_length=8, verbose_name='od')),
                ('hp', models.CharField(max_length=8, verbose_name='hp')),
                ('star', models.CharField(max_length=8, verbose_name='star')),
                ('url', models.CharField(max_length=256, verbose_name='cs')),
                ('bpm', models.CharField(max_length=8, verbose_name='bpm')),
                ('length', models.CharField(max_length=32, verbose_name='length')),
                ('mid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map_crawler.Info')),
            ],
        ),
        migrations.AddField(
            model_name='ctbdiff',
            name='mid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map_crawler.Info'),
        ),
    ]
