# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osu_pp', models.CharField(max_length=8, verbose_name='cs')),
                ('osu_rank', models.CharField(max_length=20, verbose_name='cs')),
                ('osu_bonus_pp', models.CharField(max_length=3, verbose_name='cs')),
                ('taiko_pp', models.CharField(max_length=8, verbose_name='cs')),
                ('taiko_rank', models.CharField(max_length=20, verbose_name='cs')),
                ('taiko_bonus_pp', models.CharField(max_length=3, verbose_name='cs')),
                ('ctb_pp', models.CharField(max_length=8, verbose_name='cs')),
                ('ctb_rank', models.CharField(max_length=20, verbose_name='cs')),
                ('ctb_bonus_pp', models.CharField(max_length=3, verbose_name='cs')),
                ('mania_pp', models.CharField(max_length=8, verbose_name='cs')),
                ('mania_rank', models.CharField(max_length=20, verbose_name='cs')),
                ('mania_bonus_pp', models.CharField(max_length=3, verbose_name='cs')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=256, verbose_name='mapid')),
                ('name', models.CharField(max_length=256, verbose_name='mapid')),
                ('avatar', models.CharField(max_length=256, verbose_name='mapid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ppoint',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp', to='user_crawler.User'),
        ),
    ]
